/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Guess {
  'guess' : string,
  'targetId' : PlayerId,
  'guesserId' : PlayerId,
}
export interface GuessingResult {
  'correctCount' : bigint,
  'guesses' : Array<Guess>,
}
export interface PersonalityCard { 'trait' : string }
export type Phase = { 'results' : null } |
  { 'topicSelection' : null } |
  { 'waiting' : null } |
  { 'chatting' : null } |
  { 'guessing' : null };
export type PlayerId = string;
export interface PlayerView {
  'id' : PlayerId,
  'name' : string,
  'role' : string,
  'personalityCard' : [] | [PersonalityCard],
  'isAnchor' : boolean,
}
export type RoomCode = string;
export interface RoomStateView {
  'selectedTopic' : [] | [Topic],
  'generatedTopics' : Array<Topic>,
  'votes' : Array<TopicVote>,
  'chatMessages' : Array<ChatMessage>,
  'chatCountdownStartTime' : [] | [Time],
  'players' : Array<PlayerView>,
  'phase' : Phase,
  'hostId' : PlayerId,
  'roomCode' : RoomCode,
  'roundNumber' : bigint,
  'topicSelectionStartTime' : [] | [Time],
  'guesses' : Array<Guess>,
}
export type Time = bigint;
export interface Topic { 'question' : string }
export interface TopicVote { 'playerId' : PlayerId, 'topicIndex' : bigint }
export interface _SERVICE {
  'checkAndAdvancePhase' : ActorMethod<[RoomCode], undefined>,
  'createRoom' : ActorMethod<[PlayerId, string, RoomCode], undefined>,
  'getRoomPhase' : ActorMethod<[RoomCode], Phase>,
  'getRoomState' : ActorMethod<[RoomCode], RoomStateView>,
  'joinRoom' : ActorMethod<[RoomCode, PlayerId, string], undefined>,
  'playAgain' : ActorMethod<[RoomCode], undefined>,
  'sendMessage' : ActorMethod<[RoomCode, string, string], undefined>,
  'startGame' : ActorMethod<[RoomCode, PlayerId], undefined>,
  'submitGuesses' : ActorMethod<[RoomCode, Array<Guess>], GuessingResult>,
  'voteForTopic' : ActorMethod<[RoomCode, PlayerId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];