/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerId = IDL.Text;
export const RoomCode = IDL.Text;
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PersonalityCard = IDL.Record({ 'trait' : IDL.Text });
export const Player = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'personalityCard' : IDL.Opt(PersonalityCard),
  'isAnchor' : IDL.Bool,
});
export const RoomState = IDL.Record({
  'chatMessages' : IDL.Vec(ChatMessage),
  'players' : IDL.Vec(Player),
  'phase' : IDL.Variant({
    'results' : IDL.Null,
    'waiting' : IDL.Null,
    'chatting' : IDL.Null,
    'guessing' : IDL.Null,
  }),
  'hostId' : PlayerId,
  'roomCode' : RoomCode,
});

export const idlService = IDL.Service({
  'createRoom' : IDL.Func([PlayerId, IDL.Text, RoomCode], [], []),
  'getRoomState' : IDL.Func([RoomCode], [RoomState], ['query']),
  'joinRoom' : IDL.Func([RoomCode, PlayerId, IDL.Text], [], []),
  'sendMessage' : IDL.Func([RoomCode, IDL.Text, IDL.Text], [], []),
  'startGame' : IDL.Func([RoomCode, PlayerId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerId = IDL.Text;
  const RoomCode = IDL.Text;
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PersonalityCard = IDL.Record({ 'trait' : IDL.Text });
  const Player = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'personalityCard' : IDL.Opt(PersonalityCard),
    'isAnchor' : IDL.Bool,
  });
  const RoomState = IDL.Record({
    'chatMessages' : IDL.Vec(ChatMessage),
    'players' : IDL.Vec(Player),
    'phase' : IDL.Variant({
      'results' : IDL.Null,
      'waiting' : IDL.Null,
      'chatting' : IDL.Null,
      'guessing' : IDL.Null,
    }),
    'hostId' : PlayerId,
    'roomCode' : RoomCode,
  });
  
  return IDL.Service({
    'createRoom' : IDL.Func([PlayerId, IDL.Text, RoomCode], [], []),
    'getRoomState' : IDL.Func([RoomCode], [RoomState], ['query']),
    'joinRoom' : IDL.Func([RoomCode, PlayerId, IDL.Text], [], []),
    'sendMessage' : IDL.Func([RoomCode, IDL.Text, IDL.Text], [], []),
    'startGame' : IDL.Func([RoomCode, PlayerId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };