/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomCode = IDL.Text;
export const PlayerId = IDL.Text;
export const Phase = IDL.Variant({
  'results' : IDL.Null,
  'topicSelection' : IDL.Null,
  'waiting' : IDL.Null,
  'chatting' : IDL.Null,
  'guessing' : IDL.Null,
});
export const Topic = IDL.Record({ 'question' : IDL.Text });
export const TopicVote = IDL.Record({
  'playerId' : PlayerId,
  'topicIndex' : IDL.Nat,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PersonalityCard = IDL.Record({ 'trait' : IDL.Text });
export const PlayerView = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'personalityCard' : IDL.Opt(PersonalityCard),
  'isAnchor' : IDL.Bool,
});
export const Guess = IDL.Record({
  'guess' : IDL.Text,
  'targetId' : PlayerId,
  'guesserId' : PlayerId,
});
export const RoomStateView = IDL.Record({
  'selectedTopic' : IDL.Opt(Topic),
  'generatedTopics' : IDL.Vec(Topic),
  'votes' : IDL.Vec(TopicVote),
  'chatMessages' : IDL.Vec(ChatMessage),
  'chatCountdownStartTime' : IDL.Opt(Time),
  'players' : IDL.Vec(PlayerView),
  'phase' : Phase,
  'hostId' : PlayerId,
  'roomCode' : RoomCode,
  'roundNumber' : IDL.Nat,
  'topicSelectionStartTime' : IDL.Opt(Time),
  'guesses' : IDL.Vec(Guess),
});
export const GuessingResult = IDL.Record({
  'correctCount' : IDL.Nat,
  'guesses' : IDL.Vec(Guess),
});

export const idlService = IDL.Service({
  'checkAndAdvancePhase' : IDL.Func([RoomCode], [], []),
  'createRoom' : IDL.Func([PlayerId, IDL.Text, RoomCode], [], []),
  'getRoomPhase' : IDL.Func([RoomCode], [Phase], ['query']),
  'getRoomState' : IDL.Func([RoomCode], [RoomStateView], ['query']),
  'joinRoom' : IDL.Func([RoomCode, PlayerId, IDL.Text], [], []),
  'playAgain' : IDL.Func([RoomCode], [], []),
  'sendMessage' : IDL.Func([RoomCode, IDL.Text, IDL.Text], [], []),
  'startGame' : IDL.Func([RoomCode, PlayerId], [], []),
  'submitGuesses' : IDL.Func([RoomCode, IDL.Vec(Guess)], [GuessingResult], []),
  'voteForTopic' : IDL.Func([RoomCode, PlayerId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomCode = IDL.Text;
  const PlayerId = IDL.Text;
  const Phase = IDL.Variant({
    'results' : IDL.Null,
    'topicSelection' : IDL.Null,
    'waiting' : IDL.Null,
    'chatting' : IDL.Null,
    'guessing' : IDL.Null,
  });
  const Topic = IDL.Record({ 'question' : IDL.Text });
  const TopicVote = IDL.Record({
    'playerId' : PlayerId,
    'topicIndex' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PersonalityCard = IDL.Record({ 'trait' : IDL.Text });
  const PlayerView = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'personalityCard' : IDL.Opt(PersonalityCard),
    'isAnchor' : IDL.Bool,
  });
  const Guess = IDL.Record({
    'guess' : IDL.Text,
    'targetId' : PlayerId,
    'guesserId' : PlayerId,
  });
  const RoomStateView = IDL.Record({
    'selectedTopic' : IDL.Opt(Topic),
    'generatedTopics' : IDL.Vec(Topic),
    'votes' : IDL.Vec(TopicVote),
    'chatMessages' : IDL.Vec(ChatMessage),
    'chatCountdownStartTime' : IDL.Opt(Time),
    'players' : IDL.Vec(PlayerView),
    'phase' : Phase,
    'hostId' : PlayerId,
    'roomCode' : RoomCode,
    'roundNumber' : IDL.Nat,
    'topicSelectionStartTime' : IDL.Opt(Time),
    'guesses' : IDL.Vec(Guess),
  });
  const GuessingResult = IDL.Record({
    'correctCount' : IDL.Nat,
    'guesses' : IDL.Vec(Guess),
  });
  
  return IDL.Service({
    'checkAndAdvancePhase' : IDL.Func([RoomCode], [], []),
    'createRoom' : IDL.Func([PlayerId, IDL.Text, RoomCode], [], []),
    'getRoomPhase' : IDL.Func([RoomCode], [Phase], ['query']),
    'getRoomState' : IDL.Func([RoomCode], [RoomStateView], ['query']),
    'joinRoom' : IDL.Func([RoomCode, PlayerId, IDL.Text], [], []),
    'playAgain' : IDL.Func([RoomCode], [], []),
    'sendMessage' : IDL.Func([RoomCode, IDL.Text, IDL.Text], [], []),
    'startGame' : IDL.Func([RoomCode, PlayerId], [], []),
    'submitGuesses' : IDL.Func(
        [RoomCode, IDL.Vec(Guess)],
        [GuessingResult],
        [],
      ),
    'voteForTopic' : IDL.Func([RoomCode, PlayerId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };