/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface PersonalityCard { 'trait' : string }
export interface Player {
  'id' : PlayerId,
  'name' : string,
  'personalityCard' : [] | [PersonalityCard],
  'isAnchor' : boolean,
}
export type PlayerId = string;
export type RoomCode = string;
export interface RoomState {
  'chatMessages' : Array<ChatMessage>,
  'players' : Array<Player>,
  'phase' : { 'results' : null } |
    { 'waiting' : null } |
    { 'chatting' : null } |
    { 'guessing' : null },
  'hostId' : PlayerId,
  'roomCode' : RoomCode,
}
export type Time = bigint;
export interface _SERVICE {
  'createRoom' : ActorMethod<[PlayerId, string, RoomCode], undefined>,
  'getRoomState' : ActorMethod<[RoomCode], RoomState>,
  'joinRoom' : ActorMethod<[RoomCode, PlayerId, string], undefined>,
  'sendMessage' : ActorMethod<[RoomCode, string, string], undefined>,
  'startGame' : ActorMethod<[RoomCode, PlayerId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];