/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlayerId = string;
export interface RoomState {
    chatMessages: Array<ChatMessage>;
    players: Array<Player>;
    phase: Variant_results_waiting_chatting_guessing;
    hostId: PlayerId;
    roomCode: RoomCode;
}
export interface Player {
    id: PlayerId;
    name: string;
    personalityCard?: PersonalityCard;
    isAnchor: boolean;
}
export type Time = bigint;
export type RoomCode = string;
export interface PersonalityCard {
    trait: string;
}
export interface ChatMessage {
    sender: string;
    message: string;
    timestamp: Time;
}
export enum Variant_results_waiting_chatting_guessing {
    results = "results",
    waiting = "waiting",
    chatting = "chatting",
    guessing = "guessing"
}
export interface backendInterface {
    createRoom(hostId: PlayerId, hostName: string, roomCode: RoomCode): Promise<void>;
    getRoomState(roomCode: RoomCode): Promise<RoomState>;
    joinRoom(roomCode: RoomCode, playerId: PlayerId, playerName: string): Promise<void>;
    sendMessage(roomCode: RoomCode, sender: string, message: string): Promise<void>;
    startGame(roomCode: RoomCode, hostId: PlayerId): Promise<void>;
}
import type { ChatMessage as _ChatMessage, PersonalityCard as _PersonalityCard, Player as _Player, PlayerId as _PlayerId, RoomCode as _RoomCode, RoomState as _RoomState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createRoom(arg0: PlayerId, arg1: string, arg2: RoomCode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1, arg2);
            return result;
        }
    }
    async getRoomState(arg0: RoomCode): Promise<RoomState> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomState(arg0);
                return from_candid_RoomState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomState(arg0);
            return from_candid_RoomState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRoom(arg0: RoomCode, arg1: PlayerId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1, arg2);
            return result;
        }
    }
    async sendMessage(arg0: RoomCode, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async startGame(arg0: RoomCode, arg1: PlayerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Player_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RoomState_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomState): RoomState {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonalityCard]): PersonalityCard | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chatMessages: Array<_ChatMessage>;
    players: Array<_Player>;
    phase: {
        results: null;
    } | {
        waiting: null;
    } | {
        chatting: null;
    } | {
        guessing: null;
    };
    hostId: _PlayerId;
    roomCode: _RoomCode;
}): {
    chatMessages: Array<ChatMessage>;
    players: Array<Player>;
    phase: Variant_results_waiting_chatting_guessing;
    hostId: PlayerId;
    roomCode: RoomCode;
} {
    return {
        chatMessages: value.chatMessages,
        players: from_candid_vec_n3(_uploadFile, _downloadFile, value.players),
        phase: from_candid_variant_n7(_uploadFile, _downloadFile, value.phase),
        hostId: value.hostId,
        roomCode: value.roomCode
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    name: string;
    personalityCard: [] | [_PersonalityCard];
    isAnchor: boolean;
}): {
    id: PlayerId;
    name: string;
    personalityCard?: PersonalityCard;
    isAnchor: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        personalityCard: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.personalityCard)),
        isAnchor: value.isAnchor
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    results: null;
} | {
    waiting: null;
} | {
    chatting: null;
} | {
    guessing: null;
}): Variant_results_waiting_chatting_guessing {
    return "results" in value ? Variant_results_waiting_chatting_guessing.results : "waiting" in value ? Variant_results_waiting_chatting_guessing.waiting : "chatting" in value ? Variant_results_waiting_chatting_guessing.chatting : "guessing" in value ? Variant_results_waiting_chatting_guessing.guessing : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
